### ISSUE TITLE
Version Problem

### ISSUE THREAD

**Issue by doctor35** [MaxRocamora/MayaShaderLibrary#3]
Hello Mr.  @MaxRocamora ,
I wanted to try his script on the 2020 version of maya, unfortunately since his latest update it is no longer possible to download that version. I was wondering if it was possible to create a folder named Old for those who still use versions prior to phyton 3.0.
Thanks in advance

**Comment by MaxRocamora** [comment]
Hi Doc, I have no plans for keep supporting python 2.7, I suggest to take the leap to maya 2022+ since almost everything is python 3 compatible now.
